###
post http://localhost:9000/api/movies
Content-Type: application/json

{
   "pageSize" : 1,
   "limit": 30
}

###
post http://localhost:9000/api/searchbytext
Content-Type: application/json

{
   "searchText" : "100", 
}
###
GET http://localhost:9000/api/movie/573a1391f29313caabcd73f4
###
GET http://localhost:9000/api/theaters
###
GET http://localhost:9000/api/theater/59a47286cfa9a3a73e51e72c

###
GET http://localhost:9000/api/users
###
GET http://localhost:9000/api/user/59a47286cfa9a3a73e51e72c